-- ========================================================================
-- Data Quality Check SQL generated by dq_quality_agent
-- table       : ads.ads_medr_inpatient_patient_fy_info_d_i
-- partition   : dt=2026-05-09
-- generated_at: 2026-05-09 07:32:55
-- ========================================================================
SET hive.exec.dynamic.partition = true;
SET hive.exec.dynamic.partition.mode = nonstrict;
SET hive.vectorized.execution.enabled = true;

WITH base AS (
  SELECT
    `organiz_code`,
    `inpatient_no`,
    `settlement_id`,
    `charge_id`,
    `referenced_invoice_id`,
    `charge_type`,
    `charge_name`,
    `charge_amount`,
    `pay_amount`,
    `refund_amount`,
    `pay_time`,
    `create_time`,
    `dt`
  FROM ads.ads_medr_inpatient_patient_fy_info_d_i
  WHERE dt = '2026-05-09'
)
, valid_code_fee_item AS (
  SELECT DISTINCT TRIM(CAST(value_code AS STRING)) AS value_code
  FROM dim_standard_code
  WHERE standard_encode = 'FEE_ITEM'
)
, error_check AS (
  SELECT
    'ads_medr_inpatient_patient_fy_info_d_i__partition_not_empty' AS rule_id,
    'ads.ads_medr_inpatient_patient_fy_info_d_i' AS table_name,
    'PARTITION_NOT_EMPTY' AS rule_type,
    'dt' AS field_name,
    CAST(s.cnt AS STRING) AS field_value,
    '__partition__' AS biz_key,
    '分区 dt=${biz_date} 无数据' AS error_reason,
    'CRITICAL' AS severity,
    current_timestamp() AS check_time
  FROM (SELECT COUNT(1) AS cnt FROM base) s
  WHERE s.cnt = 0
  UNION ALL
  SELECT
    'ads_medr_inpatient_patient_fy_info_d_i__unique_key__organiz_code_inpatient_no_settlement_id_charge_id' AS rule_id,
    'ads.ads_medr_inpatient_patient_fy_info_d_i' AS table_name,
    'UNIQUE_KEY' AS rule_type,
    'organiz_code,inpatient_no,settlement_id,charge_id' AS field_name,
    concat_ws('|', concat('organiz_code=', nvl(CAST(t.`organiz_code` AS STRING), 'NULL')), concat('inpatient_no=', nvl(CAST(t.`inpatient_no` AS STRING), 'NULL')), concat('settlement_id=', nvl(CAST(t.`settlement_id` AS STRING), 'NULL')), concat('charge_id=', nvl(CAST(t.`charge_id` AS STRING), 'NULL'))) AS field_value,
    concat_ws('|', concat('organiz_code=', nvl(CAST(t.`organiz_code` AS STRING), 'NULL')), concat('inpatient_no=', nvl(CAST(t.`inpatient_no` AS STRING), 'NULL')), concat('settlement_id=', nvl(CAST(t.`settlement_id` AS STRING), 'NULL')), concat('charge_id=', nvl(CAST(t.`charge_id` AS STRING), 'NULL'))) AS biz_key,
    '主键组合重复' AS error_reason,
    'CRITICAL' AS severity,
    current_timestamp() AS check_time
  FROM base t JOIN (SELECT `organiz_code`, `inpatient_no`, `settlement_id`, `charge_id`, COUNT(1) AS duplicate_cnt FROM base GROUP BY `organiz_code`, `inpatient_no`, `settlement_id`, `charge_id` HAVING COUNT(1) > 1) d ON ((t.`organiz_code` = d.`organiz_code`) OR (t.`organiz_code` IS NULL AND d.`organiz_code` IS NULL)) AND ((t.`inpatient_no` = d.`inpatient_no`) OR (t.`inpatient_no` IS NULL AND d.`inpatient_no` IS NULL)) AND ((t.`settlement_id` = d.`settlement_id`) OR (t.`settlement_id` IS NULL AND d.`settlement_id` IS NULL)) AND ((t.`charge_id` = d.`charge_id`) OR (t.`charge_id` IS NULL AND d.`charge_id` IS NULL))
  UNION ALL
  SELECT
    'ads_medr_inpatient_patient_fy_info_d_i__not_null__organiz_code' AS rule_id,
    'ads.ads_medr_inpatient_patient_fy_info_d_i' AS table_name,
    'NOT_NULL' AS rule_type,
    'organiz_code' AS field_name,
    CAST(NULL AS STRING) AS field_value,
    concat_ws('|', concat('organiz_code=', nvl(CAST(t.`organiz_code` AS STRING), 'NULL')), concat('inpatient_no=', nvl(CAST(t.`inpatient_no` AS STRING), 'NULL')), concat('settlement_id=', nvl(CAST(t.`settlement_id` AS STRING), 'NULL')), concat('charge_id=', nvl(CAST(t.`charge_id` AS STRING), 'NULL'))) AS biz_key,
    '字段 organiz_code 为空' AS error_reason,
    'CRITICAL' AS severity,
    current_timestamp() AS check_time
  FROM base t
  WHERE t.`organiz_code` IS NULL OR TRIM(CAST(t.`organiz_code` AS STRING)) = ''
  UNION ALL
  SELECT
    'ads_medr_inpatient_patient_fy_info_d_i__not_null__inpatient_no' AS rule_id,
    'ads.ads_medr_inpatient_patient_fy_info_d_i' AS table_name,
    'NOT_NULL' AS rule_type,
    'inpatient_no' AS field_name,
    CAST(NULL AS STRING) AS field_value,
    concat_ws('|', concat('organiz_code=', nvl(CAST(t.`organiz_code` AS STRING), 'NULL')), concat('inpatient_no=', nvl(CAST(t.`inpatient_no` AS STRING), 'NULL')), concat('settlement_id=', nvl(CAST(t.`settlement_id` AS STRING), 'NULL')), concat('charge_id=', nvl(CAST(t.`charge_id` AS STRING), 'NULL'))) AS biz_key,
    '字段 inpatient_no 为空' AS error_reason,
    'CRITICAL' AS severity,
    current_timestamp() AS check_time
  FROM base t
  WHERE t.`inpatient_no` IS NULL OR TRIM(CAST(t.`inpatient_no` AS STRING)) = ''
  UNION ALL
  SELECT
    'ads_medr_inpatient_patient_fy_info_d_i__not_null__settlement_id' AS rule_id,
    'ads.ads_medr_inpatient_patient_fy_info_d_i' AS table_name,
    'NOT_NULL' AS rule_type,
    'settlement_id' AS field_name,
    CAST(NULL AS STRING) AS field_value,
    concat_ws('|', concat('organiz_code=', nvl(CAST(t.`organiz_code` AS STRING), 'NULL')), concat('inpatient_no=', nvl(CAST(t.`inpatient_no` AS STRING), 'NULL')), concat('settlement_id=', nvl(CAST(t.`settlement_id` AS STRING), 'NULL')), concat('charge_id=', nvl(CAST(t.`charge_id` AS STRING), 'NULL'))) AS biz_key,
    '字段 settlement_id 为空' AS error_reason,
    'CRITICAL' AS severity,
    current_timestamp() AS check_time
  FROM base t
  WHERE t.`settlement_id` IS NULL OR TRIM(CAST(t.`settlement_id` AS STRING)) = ''
  UNION ALL
  SELECT
    'ads_medr_inpatient_patient_fy_info_d_i__not_null__charge_id' AS rule_id,
    'ads.ads_medr_inpatient_patient_fy_info_d_i' AS table_name,
    'NOT_NULL' AS rule_type,
    'charge_id' AS field_name,
    CAST(NULL AS STRING) AS field_value,
    concat_ws('|', concat('organiz_code=', nvl(CAST(t.`organiz_code` AS STRING), 'NULL')), concat('inpatient_no=', nvl(CAST(t.`inpatient_no` AS STRING), 'NULL')), concat('settlement_id=', nvl(CAST(t.`settlement_id` AS STRING), 'NULL')), concat('charge_id=', nvl(CAST(t.`charge_id` AS STRING), 'NULL'))) AS biz_key,
    '字段 charge_id 为空' AS error_reason,
    'CRITICAL' AS severity,
    current_timestamp() AS check_time
  FROM base t
  WHERE t.`charge_id` IS NULL OR TRIM(CAST(t.`charge_id` AS STRING)) = ''
  UNION ALL
  SELECT
    'ads_medr_inpatient_patient_fy_info_d_i__not_null__charge_type' AS rule_id,
    'ads.ads_medr_inpatient_patient_fy_info_d_i' AS table_name,
    'NOT_NULL' AS rule_type,
    'charge_type' AS field_name,
    CAST(NULL AS STRING) AS field_value,
    concat_ws('|', concat('organiz_code=', nvl(CAST(t.`organiz_code` AS STRING), 'NULL')), concat('inpatient_no=', nvl(CAST(t.`inpatient_no` AS STRING), 'NULL')), concat('settlement_id=', nvl(CAST(t.`settlement_id` AS STRING), 'NULL')), concat('charge_id=', nvl(CAST(t.`charge_id` AS STRING), 'NULL'))) AS biz_key,
    '字段 charge_type 为空' AS error_reason,
    'HIGH' AS severity,
    current_timestamp() AS check_time
  FROM base t
  WHERE t.`charge_type` IS NULL OR TRIM(CAST(t.`charge_type` AS STRING)) = ''
  UNION ALL
  SELECT
    'ads_medr_inpatient_patient_fy_info_d_i__enum_code__charge_type__FEE_ITEM' AS rule_id,
    'ads.ads_medr_inpatient_patient_fy_info_d_i' AS table_name,
    'ENUM_CODE' AS rule_type,
    'charge_type' AS field_name,
    CAST(t.`charge_type` AS STRING) AS field_value,
    concat_ws('|', concat('organiz_code=', nvl(CAST(t.`organiz_code` AS STRING), 'NULL')), concat('inpatient_no=', nvl(CAST(t.`inpatient_no` AS STRING), 'NULL')), concat('settlement_id=', nvl(CAST(t.`settlement_id` AS STRING), 'NULL')), concat('charge_id=', nvl(CAST(t.`charge_id` AS STRING), 'NULL'))) AS biz_key,
    '字段 charge_type 不在标准码表 FEE_ITEM 中' AS error_reason,
    'HIGH' AS severity,
    current_timestamp() AS check_time
  FROM base t LEFT JOIN valid_code_fee_item c ON TRIM(CAST(t.`charge_type` AS STRING)) = c.value_code
  WHERE t.`charge_type` IS NOT NULL AND TRIM(CAST(t.`charge_type` AS STRING)) <> '' AND c.value_code IS NULL
  UNION ALL
  SELECT
    'ads_medr_inpatient_patient_fy_info_d_i__not_null__charge_amount' AS rule_id,
    'ads.ads_medr_inpatient_patient_fy_info_d_i' AS table_name,
    'NOT_NULL' AS rule_type,
    'charge_amount' AS field_name,
    CAST(NULL AS STRING) AS field_value,
    concat_ws('|', concat('organiz_code=', nvl(CAST(t.`organiz_code` AS STRING), 'NULL')), concat('inpatient_no=', nvl(CAST(t.`inpatient_no` AS STRING), 'NULL')), concat('settlement_id=', nvl(CAST(t.`settlement_id` AS STRING), 'NULL')), concat('charge_id=', nvl(CAST(t.`charge_id` AS STRING), 'NULL'))) AS biz_key,
    '字段 charge_amount 为空' AS error_reason,
    'HIGH' AS severity,
    current_timestamp() AS check_time
  FROM base t
  WHERE t.`charge_amount` IS NULL OR TRIM(CAST(t.`charge_amount` AS STRING)) = ''
  UNION ALL
  SELECT
    'ads_medr_inpatient_patient_fy_info_d_i__non_negative__charge_amount' AS rule_id,
    'ads.ads_medr_inpatient_patient_fy_info_d_i' AS table_name,
    'NON_NEGATIVE' AS rule_type,
    'charge_amount' AS field_name,
    CAST(t.`charge_amount` AS STRING) AS field_value,
    concat_ws('|', concat('organiz_code=', nvl(CAST(t.`organiz_code` AS STRING), 'NULL')), concat('inpatient_no=', nvl(CAST(t.`inpatient_no` AS STRING), 'NULL')), concat('settlement_id=', nvl(CAST(t.`settlement_id` AS STRING), 'NULL')), concat('charge_id=', nvl(CAST(t.`charge_id` AS STRING), 'NULL'))) AS biz_key,
    '金额/费用字段 charge_amount 小于 0' AS error_reason,
    'MEDIUM' AS severity,
    current_timestamp() AS check_time
  FROM base t
  WHERE t.`charge_amount` IS NOT NULL AND CAST(t.`charge_amount` AS DOUBLE) < 0
  UNION ALL
  SELECT
    'ads_medr_inpatient_patient_fy_info_d_i__non_negative__pay_amount' AS rule_id,
    'ads.ads_medr_inpatient_patient_fy_info_d_i' AS table_name,
    'NON_NEGATIVE' AS rule_type,
    'pay_amount' AS field_name,
    CAST(t.`pay_amount` AS STRING) AS field_value,
    concat_ws('|', concat('organiz_code=', nvl(CAST(t.`organiz_code` AS STRING), 'NULL')), concat('inpatient_no=', nvl(CAST(t.`inpatient_no` AS STRING), 'NULL')), concat('settlement_id=', nvl(CAST(t.`settlement_id` AS STRING), 'NULL')), concat('charge_id=', nvl(CAST(t.`charge_id` AS STRING), 'NULL'))) AS biz_key,
    '金额/费用字段 pay_amount 小于 0' AS error_reason,
    'MEDIUM' AS severity,
    current_timestamp() AS check_time
  FROM base t
  WHERE t.`pay_amount` IS NOT NULL AND CAST(t.`pay_amount` AS DOUBLE) < 0
  UNION ALL
  SELECT
    'ads_medr_inpatient_patient_fy_info_d_i__non_negative__refund_amount' AS rule_id,
    'ads.ads_medr_inpatient_patient_fy_info_d_i' AS table_name,
    'NON_NEGATIVE' AS rule_type,
    'refund_amount' AS field_name,
    CAST(t.`refund_amount` AS STRING) AS field_value,
    concat_ws('|', concat('organiz_code=', nvl(CAST(t.`organiz_code` AS STRING), 'NULL')), concat('inpatient_no=', nvl(CAST(t.`inpatient_no` AS STRING), 'NULL')), concat('settlement_id=', nvl(CAST(t.`settlement_id` AS STRING), 'NULL')), concat('charge_id=', nvl(CAST(t.`charge_id` AS STRING), 'NULL'))) AS biz_key,
    '金额/费用字段 refund_amount 小于 0' AS error_reason,
    'MEDIUM' AS severity,
    current_timestamp() AS check_time
  FROM base t
  WHERE t.`refund_amount` IS NOT NULL AND CAST(t.`refund_amount` AS DOUBLE) < 0
  UNION ALL
  SELECT
    'ads_medr_inpatient_patient_fy_info_d_i__future_date__pay_time' AS rule_id,
    'ads.ads_medr_inpatient_patient_fy_info_d_i' AS table_name,
    'FUTURE_DATE' AS rule_type,
    'pay_time' AS field_name,
    CAST(t.`pay_time` AS STRING) AS field_value,
    concat_ws('|', concat('organiz_code=', nvl(CAST(t.`organiz_code` AS STRING), 'NULL')), concat('inpatient_no=', nvl(CAST(t.`inpatient_no` AS STRING), 'NULL')), concat('settlement_id=', nvl(CAST(t.`settlement_id` AS STRING), 'NULL')), concat('charge_id=', nvl(CAST(t.`charge_id` AS STRING), 'NULL'))) AS biz_key,
    '日期时间字段 pay_time 晚于业务日期后一天' AS error_reason,
    'MEDIUM' AS severity,
    current_timestamp() AS check_time
  FROM base t
  WHERE t.`pay_time` IS NOT NULL AND to_date(CAST(t.`pay_time` AS STRING)) > date_add('2026-05-09', 1)
  UNION ALL
  SELECT
    'ads_medr_inpatient_patient_fy_info_d_i__future_date__create_time' AS rule_id,
    'ads.ads_medr_inpatient_patient_fy_info_d_i' AS table_name,
    'FUTURE_DATE' AS rule_type,
    'create_time' AS field_name,
    CAST(t.`create_time` AS STRING) AS field_value,
    concat_ws('|', concat('organiz_code=', nvl(CAST(t.`organiz_code` AS STRING), 'NULL')), concat('inpatient_no=', nvl(CAST(t.`inpatient_no` AS STRING), 'NULL')), concat('settlement_id=', nvl(CAST(t.`settlement_id` AS STRING), 'NULL')), concat('charge_id=', nvl(CAST(t.`charge_id` AS STRING), 'NULL'))) AS biz_key,
    '日期时间字段 create_time 晚于业务日期后一天' AS error_reason,
    'MEDIUM' AS severity,
    current_timestamp() AS check_time
  FROM base t
  WHERE t.`create_time` IS NOT NULL AND to_date(CAST(t.`create_time` AS STRING)) > date_add('2026-05-09', 1)
  UNION ALL
  SELECT
    'ads_medr_inpatient_patient_fy_info_d_i__not_null__dt' AS rule_id,
    'ads.ads_medr_inpatient_patient_fy_info_d_i' AS table_name,
    'NOT_NULL' AS rule_type,
    'dt' AS field_name,
    CAST(NULL AS STRING) AS field_value,
    concat_ws('|', concat('organiz_code=', nvl(CAST(t.`organiz_code` AS STRING), 'NULL')), concat('inpatient_no=', nvl(CAST(t.`inpatient_no` AS STRING), 'NULL')), concat('settlement_id=', nvl(CAST(t.`settlement_id` AS STRING), 'NULL')), concat('charge_id=', nvl(CAST(t.`charge_id` AS STRING), 'NULL'))) AS biz_key,
    '字段 dt 为空' AS error_reason,
    'HIGH' AS severity,
    current_timestamp() AS check_time
  FROM base t
  WHERE t.`dt` IS NULL OR TRIM(CAST(t.`dt` AS STRING)) = ''
  UNION ALL
  SELECT
    'refund_amount_should_not_greater_than_charge_amount' AS rule_id,
    'ads.ads_medr_inpatient_patient_fy_info_d_i' AS table_name,
    'CUSTOM_SQL' AS rule_type,
    'refund_amount' AS field_name,
    CAST(t.`refund_amount` AS STRING) AS field_value,
    concat_ws('|', concat('organiz_code=', nvl(CAST(t.`organiz_code` AS STRING), 'NULL')), concat('inpatient_no=', nvl(CAST(t.`inpatient_no` AS STRING), 'NULL')), concat('settlement_id=', nvl(CAST(t.`settlement_id` AS STRING), 'NULL')), concat('charge_id=', nvl(CAST(t.`charge_id` AS STRING), 'NULL'))) AS biz_key,
    '退费金额大于费用金额' AS error_reason,
    'HIGH' AS severity,
    current_timestamp() AS check_time
  FROM base t
  WHERE nvl(CAST(t.`refund_amount` AS DOUBLE), 0) > nvl(CAST(t.`charge_amount` AS DOUBLE), 0)
  UNION ALL
  SELECT
    'pay_amount_should_not_greater_than_charge_amount' AS rule_id,
    'ads.ads_medr_inpatient_patient_fy_info_d_i' AS table_name,
    'CUSTOM_SQL' AS rule_type,
    'pay_amount' AS field_name,
    CAST(t.`pay_amount` AS STRING) AS field_value,
    concat_ws('|', concat('organiz_code=', nvl(CAST(t.`organiz_code` AS STRING), 'NULL')), concat('inpatient_no=', nvl(CAST(t.`inpatient_no` AS STRING), 'NULL')), concat('settlement_id=', nvl(CAST(t.`settlement_id` AS STRING), 'NULL')), concat('charge_id=', nvl(CAST(t.`charge_id` AS STRING), 'NULL'))) AS biz_key,
    '支付金额大于费用金额' AS error_reason,
    'MEDIUM' AS severity,
    current_timestamp() AS check_time
  FROM base t
  WHERE nvl(CAST(t.`pay_amount` AS DOUBLE), 0) > nvl(CAST(t.`charge_amount` AS DOUBLE), 0)
)
INSERT OVERWRITE TABLE dqc_check_result PARTITION (dt = '2026-05-09')
SELECT
  rule_id,
  table_name,
  rule_type,
  field_name,
  field_value,
  biz_key,
  error_reason,
  severity,
  check_time
FROM error_check
;
