from __future__ import annotations

from collections import OrderedDict
from datetime import datetime
from typing import Dict, Iterable, List

from dq_agent.models import RulePlan, RuleType, TableMeta


class HiveSqlGeneratorAgent:
    """Generate HiveSQL from planned data quality rules."""

    def __init__(self, quality_table: str = "dqc_check_result", code_table: str = "dim_standard_code"):
        self.quality_table = quality_table
        self.code_table = code_table

    def generate(self, table: TableMeta, plans: List[RulePlan], biz_date: str | None = None) -> str:
        biz_date = biz_date or table.partition_value
        enum_ctes = self._build_enum_ctes(plans)
        checks = self._build_checks(table, plans, biz_date)

        sql_lines = [
            "-- ========================================================================",
            "-- Data Quality Check SQL generated by dq_quality_agent",
            f"-- table       : {table.full_name}",
            f"-- partition   : {table.partition_column}={biz_date}",
            f"-- generated_at: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
            "-- ========================================================================",
            "SET hive.exec.dynamic.partition = true;",
            "SET hive.exec.dynamic.partition.mode = nonstrict;",
            "SET hive.vectorized.execution.enabled = true;",
            "",
            "WITH base AS (",
            "  SELECT",
            *self._base_select_columns(table),
            f"  FROM {table.full_name}",
            f"  WHERE {table.partition_column} = '{biz_date}'",
            ")",
        ]

        for cte_name, standard_encode in enum_ctes.items():
            sql_lines.extend(
                [
                    f", {cte_name} AS (",
                    "  SELECT DISTINCT TRIM(CAST(value_code AS STRING)) AS value_code",
                    f"  FROM {self.code_table}",
                    f"  WHERE standard_encode = '{self._escape_sql_literal(standard_encode)}'",
                    ")",
                ]
            )

        sql_lines.extend([
            ", error_check AS (",
            self._join_checks(checks),
            ")",
            f"INSERT OVERWRITE TABLE {self.quality_table} PARTITION (dt = '{biz_date}')",
            "SELECT",
            "  rule_id,",
            "  table_name,",
            "  rule_type,",
            "  field_name,",
            "  field_value,",
            "  biz_key,",
            "  error_reason,",
            "  severity,",
            "  check_time",
            "FROM error_check",
            ";",
            "",
        ])
        return "\n".join(sql_lines)

    @staticmethod
    def _base_select_columns(table: TableMeta) -> List[str]:
        cols = [col.name for col in table.columns]
        # Ensure partition column is available in base if not present in columns.
        if table.partition_column not in cols:
            cols.append(table.partition_column)
        lines = []
        for idx, col in enumerate(cols):
            comma = "," if idx < len(cols) - 1 else ""
            lines.append(f"    `{col}`{comma}")
        return lines

    def _build_enum_ctes(self, plans: List[RulePlan]) -> Dict[str, str]:
        enum_ctes: Dict[str, str] = OrderedDict()
        for plan in plans:
            if plan.rule_type == RuleType.ENUM_CODE.value and plan.standard_encode:
                enum_ctes[self._enum_cte_name(plan.standard_encode)] = plan.standard_encode
        return enum_ctes

    def _build_checks(self, table: TableMeta, plans: List[RulePlan], biz_date: str) -> List[str]:
        checks: List[str] = []
        for plan in plans:
            if plan.rule_type == RuleType.PARTITION_NOT_EMPTY.value:
                checks.append(self._partition_not_empty_check(table, plan))
            elif plan.rule_type == RuleType.UNIQUE_KEY.value:
                checks.append(self._unique_key_check(table, plan))
            elif plan.rule_type == RuleType.NOT_NULL.value:
                checks.append(self._not_null_check(table, plan))
            elif plan.rule_type == RuleType.ENUM_CODE.value:
                checks.append(self._enum_code_check(table, plan))
            elif plan.rule_type == RuleType.NON_NEGATIVE.value:
                checks.append(self._non_negative_check(table, plan))
            elif plan.rule_type == RuleType.FUTURE_DATE.value:
                checks.append(self._future_date_check(table, plan, biz_date))
            elif plan.rule_type == RuleType.CUSTOM_SQL.value:
                checks.append(self._custom_sql_check(table, plan))
            else:
                checks.append(self._custom_sql_check(table, plan))
        return checks

    def _select_error(
        self,
        plan: RulePlan,
        field_value_expr: str,
        biz_key_expr: str,
        from_sql: str,
        where_sql: str | None = None,
    ) -> str:
        lines = [
            "  SELECT",
            f"    '{self._escape_sql_literal(plan.rule_id)}' AS rule_id,",
            f"    '{self._escape_sql_literal(plan.table_name)}' AS table_name,",
            f"    '{self._escape_sql_literal(plan.rule_type)}' AS rule_type,",
            f"    '{self._escape_sql_literal(plan.field_name)}' AS field_name,",
            f"    {field_value_expr} AS field_value,",
            f"    {biz_key_expr} AS biz_key,",
            f"    '{self._escape_sql_literal(plan.reason)}' AS error_reason,",
            f"    '{self._escape_sql_literal(plan.severity)}' AS severity,",
            "    current_timestamp() AS check_time",
            f"  {from_sql}",
        ]
        if where_sql:
            lines.append(f"  WHERE {where_sql}")
        return "\n".join(lines)

    def _not_null_check(self, table: TableMeta, plan: RulePlan) -> str:
        col = plan.field_name
        return self._select_error(
            plan=plan,
            field_value_expr="CAST(NULL AS STRING)",
            biz_key_expr=self._biz_key_expr(table),
            from_sql="FROM base t",
            where_sql=f"t.`{col}` IS NULL OR TRIM(CAST(t.`{col}` AS STRING)) = ''",
        )

    def _enum_code_check(self, table: TableMeta, plan: RulePlan) -> str:
        col = plan.field_name
        cte = self._enum_cte_name(plan.standard_encode or "UNKNOWN")
        return self._select_error(
            plan=plan,
            field_value_expr=f"CAST(t.`{col}` AS STRING)",
            biz_key_expr=self._biz_key_expr(table),
            from_sql=f"FROM base t LEFT JOIN {cte} c ON TRIM(CAST(t.`{col}` AS STRING)) = c.value_code",
            where_sql=f"t.`{col}` IS NOT NULL AND TRIM(CAST(t.`{col}` AS STRING)) <> '' AND c.value_code IS NULL",
        )

    def _non_negative_check(self, table: TableMeta, plan: RulePlan) -> str:
        col = plan.field_name
        return self._select_error(
            plan=plan,
            field_value_expr=f"CAST(t.`{col}` AS STRING)",
            biz_key_expr=self._biz_key_expr(table),
            from_sql="FROM base t",
            where_sql=f"t.`{col}` IS NOT NULL AND CAST(t.`{col}` AS DOUBLE) < 0",
        )

    def _future_date_check(self, table: TableMeta, plan: RulePlan, biz_date: str) -> str:
        col = plan.field_name
        # Allow one-day delay because many hospital/financial systems write late night settlement data.
        return self._select_error(
            plan=plan,
            field_value_expr=f"CAST(t.`{col}` AS STRING)",
            biz_key_expr=self._biz_key_expr(table),
            from_sql="FROM base t",
            where_sql=(
                f"t.`{col}` IS NOT NULL "
                f"AND to_date(CAST(t.`{col}` AS STRING)) > date_add('{biz_date}', 1)"
            ),
        )

    def _partition_not_empty_check(self, table: TableMeta, plan: RulePlan) -> str:
        return self._select_error(
            plan=plan,
            field_value_expr="CAST(s.cnt AS STRING)",
            biz_key_expr="'__partition__'",
            from_sql="FROM (SELECT COUNT(1) AS cnt FROM base) s",
            where_sql="s.cnt = 0",
        )

    def _unique_key_check(self, table: TableMeta, plan: RulePlan) -> str:
        keys = plan.extra.get("keys") or [x.strip() for x in plan.field_name.split(",") if x.strip()]
        if not keys:
            return self._select_error(
                plan=plan,
                field_value_expr="CAST(NULL AS STRING)",
                biz_key_expr="'__no_key_configured__'",
                from_sql="FROM base t",
                where_sql="1 = 0",
            )

        group_cols = ", ".join([f"`{k}`" for k in keys])
        join_cond = " AND ".join([self._null_safe_equals(f"t.`{k}`", f"d.`{k}`") for k in keys])
        duplicate_cte = (
            "(SELECT "
            + group_cols
            + ", COUNT(1) AS duplicate_cnt FROM base GROUP BY "
            + group_cols
            + " HAVING COUNT(1) > 1) d"
        )

        field_value = "concat_ws('|', " + ", ".join([f"concat('{k}=', nvl(CAST(t.`{k}` AS STRING), 'NULL'))" for k in keys]) + ")"

        return self._select_error(
            plan=plan,
            field_value_expr=field_value,
            biz_key_expr=self._biz_key_expr(table),
            from_sql=f"FROM base t JOIN {duplicate_cte} ON {join_cond}",
            where_sql=None,
        )

    def _custom_sql_check(self, table: TableMeta, plan: RulePlan) -> str:
        expression = plan.expression or "1 = 0"
        field = plan.field_name
        if field == "*":
            field_value = "CAST(NULL AS STRING)"
        else:
            field_value = f"CAST(t.`{field}` AS STRING)"
        return self._select_error(
            plan=plan,
            field_value_expr=field_value,
            biz_key_expr=self._biz_key_expr(table),
            from_sql="FROM base t",
            where_sql=expression,
        )

    @staticmethod
    def _join_checks(checks: Iterable[str]) -> str:
        checks = list(checks)
        if not checks:
            return (
                "  SELECT 'no_rule' AS rule_id, 'unknown' AS table_name, 'NO_RULE' AS rule_type, "
                "'*' AS field_name, CAST(NULL AS STRING) AS field_value, '__none__' AS biz_key, "
                "'no rule configured' AS error_reason, 'LOW' AS severity, current_timestamp() AS check_time "
                "WHERE 1 = 0"
            )
        return "\n  UNION ALL\n".join(checks)

    def _biz_key_expr(self, table: TableMeta) -> str:
        keys = table.primary_keys or [c.name for c in table.columns[:3]]
        if not keys:
            return "'__no_biz_key__'"
        parts = [f"concat('{k}=', nvl(CAST(t.`{k}` AS STRING), 'NULL'))" for k in keys]
        return "concat_ws('|', " + ", ".join(parts) + ")"

    @staticmethod
    def _enum_cte_name(standard_encode: str) -> str:
        cleaned = "".join(ch.lower() if ch.isalnum() else "_" for ch in standard_encode)
        return f"valid_code_{cleaned}"

    @staticmethod
    def _escape_sql_literal(value: str) -> str:
        return str(value).replace("'", "''")

    @staticmethod
    def _null_safe_equals(left: str, right: str) -> str:
        return f"(({left} = {right}) OR ({left} IS NULL AND {right} IS NULL))"
